// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zeiss_api.Data;

#nullable disable

namespace zeiss_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821104557_RenameCategoryTable")]
    partial class RenameCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("zeiss_api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Office Supplies"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Furniture"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Sports & Outdoors"
                        });
                });

            modelBuilder.Entity("zeiss_api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 100001,
                            CategoryId = 1,
                            Name = "Wireless Mouse",
                            Price = 24.99m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 100002,
                            CategoryId = 1,
                            Name = "Wireless Keyboard",
                            Price = 49.99m,
                            Stock = 85
                        },
                        new
                        {
                            Id = 100003,
                            CategoryId = 1,
                            Name = "Wireless Headphones",
                            Price = 89.99m,
                            Stock = 0
                        },
                        new
                        {
                            Id = 100004,
                            CategoryId = 1,
                            Name = "USB-C Charging Cable",
                            Price = 12.99m,
                            Stock = 500
                        },
                        new
                        {
                            Id = 100005,
                            CategoryId = 2,
                            Name = "Standing Desk Converter",
                            Price = 129.99m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 100006,
                            CategoryId = 2,
                            Name = "Desk Lamp",
                            Price = 34.50m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 100007,
                            CategoryId = 2,
                            Name = "Mechanical Pencil Set",
                            Price = 8.99m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 100008,
                            CategoryId = 3,
                            Name = "Standing Desk",
                            Price = 349.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 100009,
                            CategoryId = 3,
                            Name = "Ergonomic Office Chair",
                            Price = 219.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 100010,
                            CategoryId = 4,
                            Name = "Yoga Mat",
                            Price = 19.99m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 100011,
                            CategoryId = 4,
                            Name = "Water Bottle",
                            Price = 9.99m,
                            Stock = 1000
                        });
                });

            modelBuilder.Entity("zeiss_api.Models.Product", b =>
                {
                    b.HasOne("zeiss_api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
